implemented requested changes
lxc/lxc pull request #3585
Opened 2020-11-21 01:58 UTC by AndrewElvisDeng

Signed-off-by: Andrew Deng <adeng1433@gmail.com>
Fixes #1507

2020-11-22 03:38 UTC, stgraber commented
You should also add a `--standard-resolver` CLI argument, that's pretty trivial to do by upting the getopt call and the loop after it as well as the help message.

2020-11-22 13:35 UTC, brauner requested changes
The commit message needs to be changed. "Implemented requested changes" doesn't tell us anything about what has been changed and why it has been changed. Right now I've no idea what this commit is supposed to be about. :)

2020-12-04 03:25 UTC, AndrewElvisDeng commented
@brauner @stgraber We've updated the commit messages and added the `--standard-resolver` argument

2020-12-04 15:16 UTC, stgraber commented on templates/lxc-download.in
> +
What's that about? :)

2020-12-04 15:19 UTC, stgraber commented on templates/lxc-download.in
> +[ --standard-resolver <resolver> ]: Force the use of a specific standard resolver
This shouldn't take arguments, it should just be `--standard-resolver` and if passed should set DOWNLOAD_STANDARD_RESOLVER to `true`.

2020-12-04 15:20 UTC, stgraber commented on templates/lxc-download.in
> +  if [ --standard-resolver "${STANDARD_RESOLVER:-}" ]; then
This is invalid shell, you should check for something like `"${DOWNLOAD_STANDARD_RESOLVER}" = "true"` and make sure to initialize `DOWNLOAD_STANDARD_RESOLVER` to `false` at the top of the file.

2020-12-05 22:02 UTC, AndrewElvisDeng commented on templates/lxc-download.in
> +
Don't know how that snuck in there...

2020-12-07 19:54 UTC, stgraber commented on templates/lxc-download.in
> +  if [ --standard-resolver "${DOWNLOAD_STANDARD_RESOLVER}" = "true" ]; then
That should just be `if [ "${DOWNLOAD_STANDARD_RESOLVER}" = "true" ]; then`

2020-12-07 23:56 UTC, stgraber commented on templates/lxc-download.in
> +if [ "${DOWNLOAD_STANDARD_RESOLVER}" = "true" ]; then
Indent is broken somehow

2020-12-08 15:05 UTC, stgraber commented on templates/lxc-download.in
> +    --standard-resolver) STANDARD_RESOLVER="$2"; shift 2;;
This should be:
```
--standard-resolver) STANDARD_RESOLVER="true"; shift 1;;
```

And I'd also move it up with the other flags, just under `--force-cache`

2020-12-08 19:40 UTC, stgraber commented
Looks good, can you rebase this into just a single commit?

2020-12-08 20:21 UTC, AndrewElvisDeng commented
@stgraber Done!

2020-12-08 21:52 UTC, stgraber commented
jenkins: test this please

2020-12-08 22:07 UTC, merged