fix for issue #4026: set broadcast to 0.0.0.0 for /31 and /32
lxc/lxc pull request #4147
Opened 2022-06-13 12:49 UTC by marcfiu

For /31 and /32 IPv4 addresses there is no direct broadcast address. Instead, as discussed with @tomponline for issue #4026, it should be set to 0.0.0.0.

2022-06-13 12:57 UTC, tomponline approved these changes

2022-06-13 12:58 UTC, tomponline commented
ok to test

2022-06-13 12:58 UTC, tomponline requested changes
LGTM thanks!

Please can you sign off your commit though.

2022-06-13 15:26 UTC, marcfiu commented
@tomponline : did the sign off.

2022-06-13 15:36 UTC, brauner approved these changes
The saga continues. :D

2022-06-13 15:43 UTC, tomponline commented
Oh please can you merge your commits together or use different commit messages explaining what each one does.

2022-06-27 11:17 UTC, tomponline commented
@marcfiu are you able to look at the changes requested please?

2022-07-01 00:19 UTC, marcfiu commented
@tomponline i made the requested changes earlier this week. Anything else?

2022-07-01 00:36 UTC, tomponline approved these changes
Lgtm thanks!

2022-07-01 08:16 UTC, merged

2022-07-01 08:16 UTC, brauner commented
Thank you!