meson.build: allow explicit distrosysconfdir
lxc/lxc pull request #4180
Opened 2022-08-09 15:27 UTC by sgn

Allows either:

- Build inside minimal-and-clean chroot without neither
  /etc/sysconfdir nor /etc/default.
- Cross Compile lxc from foreign distro,
  let's say host distro uses /etc/sysconfdir and build distro
  uses /etc/default and vice versus.

Fix #4178

2022-08-09 15:33 UTC, brauner approved these changes
Thank you!

2022-08-09 18:59 UTC, brauner requested changes
Thanks for the patch! Could you please sign-off your commit?

2022-08-09 19:18 UTC, eli-schwartz commented
Commit message is wrong -- it refers to "/etc/sysconfdir" but no such directory exists, it is rather "/etc/sysconfig".

*insert rant about legacy use of "distro-specific `--sysconfdir`"*

2022-08-10 00:13 UTC, sgn commented
@brauner  and @eli-schwartz  Both are done. Thanks.

2022-08-11 18:22 UTC, merged