containers in the FREEZING state also need to be unfreeze
lxc/lxc pull request #4346
Opened 2023-09-13 03:16 UTC by zhongTao99

When lxc is doing cgroup_freeze,：
```c
int cgroup_freeze(const char *name, const char *lxcpath, int timeout)
{
	__do_close int unified_fd = -EBADF;
	int ret;

	if (is_empty_string(name) || is_empty_string(lxcpath))
		return ret_errno(EINVAL);

	unified_fd = lxc_cmd_get_limit_cgroup2_fd(name, lxcpath);
	if (unified_fd < 0)
		return ret_errno(ENOCGROUP2);

	lxc_cmd_notify_state_listeners(name, lxcpath, FREEZING);
	ret = __cgroup_freeze(unified_fd, timeout);
	lxc_cmd_notify_state_listeners(name, lxcpath, !ret ? FROZEN : RUNNING);
	return ret;
}
```

if the lxc process is killed after setting the container status to FREEZING, the container status will be abnormal, unfreezing operation will not be possible, and normal life cycle management will not be possible. Therefore, containers in the FREEZING state also need to be unfreeze

2023-09-14 01:32 UTC, zhongTao99 commented
ok to test

2023-09-14 01:35 UTC, zhongTao99 commented
test this please

2023-09-14 01:36 UTC, zhongTao99 commented
jenkins: test this please

2023-09-14 03:35 UTC, zhongTao99 commented
jenkins: test this please

2023-09-15 18:37 UTC, brauner requested changes
Hm, I think unfreezing when FREEZING is racy. You need to wait for FROZEN and then unfreeze.

2023-09-17 23:21 UTC, stgraber commented
I've definitely seen containers stuck in FREEZING before, no amount of waiting would get them into FROZEN, but going back to THAWED would work fine to unstick them.

2023-09-18 02:07 UTC, zhongTao99 commented
Thanks both for your replies.
If it is a normal scenario, the status will eventually be FROZEN. But what I am confused about is if the process exits abnormally after being killed, can the status still be FROZEN?

2023-09-18 07:10 UTC, brauner commented
> Thanks both for your replies. If it is a normal scenario, the status will eventually be FROZEN. But what I am confused about is if the process exits abnormally after being killed in the FREEZING state, can the state still change to FROZEN normally?

I'm not sure I follow: if the process exits abnormally after being killed in FREEZING state then lxc_getstate() would be returning STOPPED.

2023-10-11 14:14 UTC, mihalicyn commented
> My best guess is that it was freezing in the middle of some FUSE operations and found itself stuck there.

this is very-very important point. It explains why you have get this problem.
Actually, most of FUSE operations are uninterruptible (they use `wait_event` that puts task into `TASK_UNINTERRUPTIBLE` sleep). To be freezable task should be put to the `__refrigerator` (https://github.com/torvalds/linux/blob/1c8b86a3799f7e5be903c3f49fcdaee29fd385b5/kernel/freezer.c#L62) but we can't do that when `TASK_UNINTERRUPTIBLE` is set or if task is not sleeping in a proper state (`TASK_INTERRUPTIBLE|TASK_FREEZABLE` state, for example, use `wait_event_freezable`).

2023-12-10 20:20 UTC, stgraber commented
@brauner @mihalicyn so is there an actual concern with this change?

I agree that in general FREEZING shouldn't be a state that the kernel remains stuck on, but it's a thing that's be known to happen and when it does, you can absolutely move back to THAWED, so allowing someone to do so through liblxc still seems fine to me.

2024-03-26 14:36 UTC, stgraber approved these changes

2024-03-26 14:37 UTC, merged